### ISSUE TITLE
Need to create a users.json

### ISSUE THREAD

**Issue by marek22k** [canewsin/zeronet-rs#5]
Problem: It is necessary to manually create a users.json.

```
$./zeronet 
Loading sites.json file
Loading users file
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/io/utils.rs:55:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$./zeronet 
Loading sites.json file
Loading users file
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/io/utils.rs:55:63
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/result.rs:1078:23
   4: zeronet::io::utils::load_users_file
             at /home/bandura/Downloads/zeronet-rs/src/io/utils.rs:55:26
   5: <zeronet::environment::USER_STORAGE as core::ops::deref::Deref>::deref::__static_ref_initialize
             at /home/bandura/Downloads/zeronet-rs/src/environment.rs:17:58
   6: core::ops::function::FnOnce::call_once
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/ops/function.rs:227:5
   7: lazy_static::lazy::Lazy<T>::get::{{closure}}
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:31:29
   8: std::sync::once::Once::call_once::{{closure}}
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sync/once.rs:270:41
   9: std::sync::once::Once::call_inner
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sync/once.rs:428:21
  10: std::sync::once::Once::call_once
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sync/once.rs:270:9
  11: lazy_static::lazy::Lazy<T>::get
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:30:9
  12: <zeronet::environment::USER_STORAGE as core::ops::deref::Deref>::deref::__stability
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:142:21
  13: <zeronet::environment::USER_STORAGE as core::ops::deref::Deref>::deref
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:144:17
  14: zeronet::main::{{closure}}
             at /home/bandura/Downloads/zeronet-rs/src/main.rs:26:25
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/future/mod.rs:91:19
  16: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
  17: tokio::coop::with_budget::{{closure}}
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  18: std::thread::local::LocalKey<T>::try_with
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/thread/local.rs:442:16
  19: std::thread::local::LocalKey<T>::with
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/thread/local.rs:418:9
  20: tokio::coop::with_budget
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  21: tokio::coop::budget
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  22: tokio::park::thread::CachedParkThread::block_on
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
  23: tokio::runtime::enter::Enter::block_on
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  24: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/mod.rs:73:9
  25: tokio::runtime::Runtime::block_on
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:477:43
  26: zeronet::main
             at /home/bandura/Downloads/zeronet-rs/src/main.rs:93:5
  27: core::ops::function::FnOnce::call_once
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

$./zeronet  --version
Loading sites.json file
ZeroNetX 0.8.0 r4800
```

run from zeronet-rs/target/debug

same happen when I run the binary from https://github.com/canewsin/zeronet-rs/releases

**Comment by canewsin** [comment]
Yeah, Currently users.json creation is pulled back while testing features unlike initial impl, will add back soon.

**Comment by canewsin** [comment]
Available on latest version
