### ISSUE TITLE
Failed to download zite: EOF while parsing a value

### ISSUE THREAD

**Issue by marek22k** [canewsin/zeronet-rs#6]
```
$./zeronet siteDownload -s "1Keke3V7Fn8bPt82QyhNHkv5gx5NnK9Umu"
Loading sites.json file
Loading users file
Loading user: 1FdDwDNWJLxCBoBcVtmbKgohofi7r5Wmiq
Downloading Site
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', zerucontent/src/content.rs:108:68
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/result.rs:1078:23
   4: zerucontent::content::Content::from_buf
             at /home/bandura/Downloads/zeronet-rs/zerucontent/src/content.rs:108:39
   5: zeronet::io::site::<impl zeronet::core::site::Site>::load_content::{{closure}}
             at /home/bandura/Downloads/zeronet-rs/src/io/site.rs:155:23
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/future/mod.rs:91:19
   7: zeronet::io::site::<impl zeronet::core::io::SiteIO for zeronet::core::site::Site>::init_download::{{closure}}
             at /home/bandura/Downloads/zeronet-rs/src/io/site.rs:251:43
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/future/mod.rs:91:19
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/future/future.rs:124:9
  10: zeronet::common::download_site::{{closure}}
             at /home/bandura/Downloads/zeronet-rs/src/common.rs:106:29
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/future/mod.rs:91:19
  12: zeronet::main::{{closure}}
             at /home/bandura/Downloads/zeronet-rs/src/main.rs:39:59
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/future/mod.rs:91:19
  14: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
  15: tokio::coop::with_budget::{{closure}}
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/thread/local.rs:442:16
  17: std::thread::local::LocalKey<T>::with
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/thread/local.rs:418:9
  18: tokio::coop::with_budget
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  19: tokio::coop::budget
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  20: tokio::park::thread::CachedParkThread::block_on
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
  21: tokio::runtime::enter::Enter::block_on
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  22: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/mod.rs:73:9
  23: tokio::runtime::Runtime::block_on
             at /home/bandura/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:477:43
  24: zeronet::main
             at /home/bandura/Downloads/zeronet-rs/src/main.rs:93:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by canewsin** [comment]
Fixed in latest version
